version: '2'
volumes:
  resin-data:
  config:
  server:
services:

  electron:
    build: ./electron
    privileged: true
    restart: always
    volumes:
      - 'config:/config'
    labels:
      io.balena.features.dbus: '1'
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - ELECTRON_DISABLE_SECURITY_WARNINGS=true
    depends_on:
      - server

  server:
    build: ./server
    restart: always
    volumes:
      - 'server:/server'
    ports:
      - "3000:3000"
      - "8080:8080"

